# Generated by Django 5.0 on 2024-02-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='catogory',
        ),
    ]
