# Generated by Django 5.0 on 2024-02-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0002_rename_cat_product_catogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogory',
            new_name='cat',
        ),
    ]
